### ISSUE TITLE
Cant download malware samples

### ISSUE THREAD

**Issue by potatoFry** [Vi45en/Pesidious#3]
Hi team,
Cant seem to download the test samples as they have been blocked by Share Point. How else can I obtain the samples? What kind of samples can I pass through the model?

**Comment by Chandni97** [comment]
Hello, you can download your malware samples from other malware repositories such as VirusTotal or VirusShare. Additionally, we will soon be deleting this repository and you can find the updated project here (https://github.com/CyberForce/Pesidious)
